//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated on: 2024-04-17 11:31:06
// </auto-generated>
//------------------------------------------------------------------------------

public class PersonEntity
{
    public string Name { get; set; }
    public int Age { get; set; }
    public string Email { get; set; }
}
